name: CI/CD PIPELINE

on:
  push:
    branches: [ "main"]
  pull_request:
    branches: ["main"]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v3

      - name: Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Вход в Docker-hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PASS}}

      - name: Сборка и пуш изображения Docker'а
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: kostyaokriashvili/projectnis:latest

      - name: Деплой через SSH
        if: github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd /path/to/project
            git pull origin main || true
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
            docker compose pull
            docker compose up -d --build