name: CI/CD PIPELINE

on:
  push:
    branches: [ "main"]
  pull_request:
    branches: ["main"]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v3

      - name: Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Вход в Docker-hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PASS}}

      - name: Создание файла .env на сервере
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASS }}
          port: 22
          request_pty: true
          script: |
            cat <<EOF > /home/username/.env
            DB_NAME=${{ secrets.DB_NAME }}
            DB_USER=${{ secrets.DB_USER }}
            DB_PASS=${{ secrets.DB_PASS }}
            BASE_URL=${{ secrets.BASE_URL }}
            BOT_TOKEN=${{ secrets.BOT_TOKEN }}
            PAYMENT_PROVIDER_TOKEN=${{ secrets.PAYMENT_PROVIDER_TOKEN }}
            DB_HOST=${{ secrets.DB_HOST }}
            DB_PORT=${{ secrets.DB_PORT }}
            EOF

      - name: Сборка и пуш изображения Docker'а
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: kostyaokriashvili/projectnis:latest

      - name: Копирование docker-compose.yml на сервер
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{secrets.SSH_PASS}}
          port: 22
          source: "docker-compose.yml"
          target: "/home/kostas/"

      - name: Деплой через SSH
        if: github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{secrets.SSH_PASS}}
          port: 22
          tty: true
          script: |
            cd /home/kostas/
            echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
            docker compose -f /home/kostas/docker-compose.yml  pull
            docker compose up -d --build